spring:
  application:
    name: UrlShortenerService
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/TinyUrlService
    username: postgres
    password: 676128

url:
  fe-domain: localhost3000/
  hash-length: 6
  base62: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789

security:
  allowed:
    origins: http://localhost:5173
    origin:
      methods: GET,POST,PUT,DELETE,OPTIONS
